<?php
namespace app\system\controller;
/*
* Created by PhpStorm.
* Author: 初心 [jialin507@foxmail.com]
* Date: 2017/4/27
*/
use app\base\controller\Base;
use app\system\model\Config as ConfigModel;
use think\Cache;
use think\Config as ConfigSettings;
class Config extends Base{
    protected $config_model;

    protected function _initialize(){
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->config_model = new ConfigModel();
    }

    public function configList($group = 0){
        if($this->request->isAjax()){
            return $this->getConfig();
        }
        $this->view->assign('config_type_list',ConfigSettings::get('config_type_list'));
        $this->view->assign('config_group_list',ConfigSettings::get('config_group_list'));
        $this->view->assign('group', $group);
        return $this->view->fetch();
    }

    /**
     * 新增，修改
     * @return array|string
     */
    public function save() {
        if($this->request->isAjax()){
            $post_data = $this->request->param();
            if(empty($post_data)){return getMsg("数据不能为空");}
            $menu = new ConfigModel();
            $state = $menu->allowField(true)->save($post_data,$post_data['id']);
            if(false == $state){
                return getMsg("操作失败");
            }
            return getMsg("操作成功");
        }
    }

    /**
     * ajax 获取配置列表
     * @param int $pid
     * @param int $p
     * @return mixed
     */
    public function getConfig($group = 0, $p = 1, $keyword = '') {
        $config = new ConfigModel();
        $p = ($p*10) - 10;
        $list = $config->getConfig($keyword, $group, $p);
        $msg['status'] = 200;
        $msg['data']['list'] = $this->getName($list);
        $msg['pages'] = $config->getPage($group);
        return $msg;
    }

    public function getName($lists){
        foreach ($lists as &$value){
            $value['type_name'] = get_config_type_value($value['type']);
            if($value['group'] == 0){
                $value['group_name'] = '';
            }else{
                $value['group_name'] = get_config_group_value($value['group']);
            }
        }
        return $lists;
    }

    public function setconfig1($id = 1) {
        $config = new ConfigModel();
        $list = $config->getConfig('',$id,0,999);

        $this->assign('list','');
        $this->assign('id','');
        return $this->view->fetch();
    }

    /**
     * 配置设置
     * @return mixed
     */
    public function setConfig(){
        //配置分组
        $group_config = ConfigSettings::get("CONFIG_GROUP_LIST");
        $this->assign('group_config',$group_config);

        //分组配置
        $group_id = $this->request->param('group_id') ? $this->request->param('group_id') : 1;
        $group_data = $this->config_model->where(['group'=>$group_id,'status'=>1])->select()->toArray();
        $this->assign('group_data',$group_data);
        $this->assign('group_id',$group_id);

        return $this->fetch();
    }

    /**
     * 修改配置值
     * @return array|string
     */
    public function saveConfig(){
        $config_datas = $this->request->param()['config'];
        foreach ($config_datas as $key => $value){
            $this->config_model->where(['name'=>$key])->setField('value', $value);
        }
        Cache::rm('cache_config');
        return getMsg("操作成功");
    }

    /**
     * 修改配置内容
     * @return array|string
     */
    public function updateconfig() {
        if($this->request->isAjax()){
            $config = $this->request->param();
            if($config && is_array($config)){
                $configModel = new ConfigModel();
                foreach ($config as $name => $value){
                    $map['name'] = $name;
                    $configModel->where($map)->setField('value', $value);
                }
            }
            Cache::rm('cache_config');
            return getMsg("操作成功");
        }
    }

}
